services:
  vellmes-ssh:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    container_name: vellmes-ssh
    ports:
      - "${SSH_PORT:-22}:22"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL=${MODEL}
      - MAX_TOKENS=${MAX_TOKENS}
      - TEMPERATURE=${TEMPERATURE}
    volumes:
      - ./app/configs:/app/configs
      - ./Logs/SSH:/app/Logs/SSH
      - ./Conversations/SSH:/app/Conversations/SSH
    restart: unless-stopped
    networks:
      - vellmes-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vellmes-http:
    build:
      context: .
      dockerfile: Dockerfile.http
    container_name: vellmes-http
    ports:
      - "${HTTP_PORT:-80}:80"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL=${MODEL}
      - MAX_TOKENS=${MAX_TOKENS}
      - TEMPERATURE=${TEMPERATURE}
    volumes:
      - ./app/configs:/app/configs
      - ./Logs/HTTP:/app/Logs/HTTP
      - ./Conversations/HTTP:/app/Conversations/HTTP
    restart: unless-stopped
    networks:
      - vellmes-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  vellmes-mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: vellmes-mysql
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - MODEL=${MODEL}
      - MAX_TOKENS=${MAX_TOKENS}
      - TEMPERATURE=${TEMPERATURE}
    volumes:
      - ./Logs/MySQL:/app/Logs/MySQL
      - ./Conversations/MySQL:/app/Conversations/MySQL
    restart: unless-stopped
    networks:
      - vellmes-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  scenario_generator:
    build:
      context: .
      dockerfile: Dockerfile.ssh
    container_name: vellmes-generator
    volumes:
      - ./app/configs:/app/configs
    command: ["sh", "-c", "while true; do python /app/configs/Gemini_Create_Promt.py; sleep 21600; done"]
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    networks:
      - vellmes-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  vellmes-network:
    driver: bridge